#include "input_maps.hpp"

#include <QtCore/qnamespace.h>
#include <SDL3/SDL_scancode.h>

#include <algorithm>
#include <cctype>
#include <cstddef>
#include <string_view>
#include <utility>

namespace goliath {

namespace {

std::string trim_input_value(const std::string& value) {
    const std::size_t start = value.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) return {};
    const std::size_t end = value.find_last_not_of(" \t\r\n");
    return value.substr(start, end - start + 1);
}

std::optional<int> decimal_in_range(std::string_view text,
                                    int minimum,
                                    int maximum) {
    if (text.empty()) return std::nullopt;

    int value = 0;
    for (const char ch : text) {
        if (!std::isdigit(static_cast<unsigned char>(ch)))
            return std::nullopt;
        value = value * 10 + (ch - '0');
        if (value > maximum) return std::nullopt;
    }
    return value >= minimum ? std::optional<int>(value) : std::nullopt;
}

bool is_known_input_definition(const std::string& section,
                               const std::string& key) {
    const auto sectionIt = input_defs().find(section);
    if (sectionIt == input_defs().end()) return false;
    return std::find(sectionIt->second.begin(), sectionIt->second.end(), key) !=
           sectionIt->second.end();
}

bool is_safe_jgrf_binding(const std::string& value,
                          bool analogDefinition) {
    if (value.empty()) return false;

    if (value[0] == 'j') {
        // JGRF 2.0.1 reads the frontend port directly from value[1], so only
        // the single-digit form generated by its own input configurator is
        // safe here.
        if (value.size() < 4 || value[1] < '0' || value[1] > '9')
            return false;

        if (value[2] == 'a') {
            if (value[3] < '0' ||
                value[3] >= '0' + kJgrfJoystickAxisCount) {
                return false;
            }
            if (analogDefinition) return value.size() == 4;
            return value.size() == 5 &&
                   (value[4] == '+' || value[4] == '-');
        }

        if (analogDefinition) return false;
        if (value[2] == 'b') {
            return decimal_in_range(
                       std::string_view(value).substr(3), 0,
                       kJgrfJoystickButtonCount - 1)
                .has_value();
        }
        if (value[2] == 'h') {
            return value.size() == 5 && value[3] == '0' &&
                   value[4] >= '0' &&
                   value[4] < '0' + kJgrfHatDirectionCount;
        }
        return false;
    }

    if (analogDefinition) return false;
    if (value.starts_with("mb")) {
        return decimal_in_range(
                   std::string_view(value).substr(2), 0,
                   kJgrfJoystickButtonCount - 1)
            .has_value();
    }

    return decimal_in_range(value, 0, SDL_SCANCODE_COUNT - 1).has_value();
}

} // namespace

const std::map<std::string, std::vector<std::string>>& input_defs() {
    static const std::map<std::string, std::vector<std::string>> defs = {
        {"neogeojs1", {"Up", "Down", "Left", "Right", "Select", "Start", "A", "B", "C", "D"}},
        {"neogeojs2", {"Up", "Down", "Left", "Right", "Select", "Start", "A", "B", "C", "D"}},
        {"neogeojs3", {"Up", "Down", "Left", "Right", "Select", "Start", "A", "B", "C", "D"}},
        {"neogeojs4", {"Up", "Down", "Left", "Right", "Select", "Start", "A", "B", "C", "D"}},
        {"neogeosystem", {"Coin1", "Coin2", "Service", "Test"}},
        {"neogeomahjong", {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N",
                            "Pon", "Chi", "Kan", "Reach", "Ron", "Select", "Start"}},
        {"neogeovliner", {"Up", "Down", "Left", "Right", "Big", "Small", "D-Up", "Start",
                           "Operator", "ClearCredit", "HopperOut"}},
        {"neogeoirrmaze", {"XAxis", "YAxis", "LeftA", "LeftB", "RightA", "RightB", "Start"}},
    };
    return defs;
}

const std::map<std::string, std::map<std::string, std::string>>& default_input_config() {
    static const std::map<std::string, std::map<std::string, std::string>> defs = {
        {"neogeosystem", {{"Coin1", "34"}, {"Coin2", "31"}, {"Service", "35"}, {"Test", "36"}}},
        {"neogeojs1", {
            {"Up", "26"}, {"Down", "22"}, {"Left", "4"}, {"Right", "7"},
            {"Select", "33"}, {"Start", "30"},
            {"A", "13"}, {"B", "14"}, {"C", "24"}, {"D", "12"},
        }},
    };
    return defs;
}

const std::map<int, std::string>& sdl_scancode_names() {
    static const std::map<int, std::string> names = {
        {4, "a"}, {5, "b"}, {6, "c"}, {7, "d"}, {8, "e"}, {9, "f"}, {10, "g"}, {11, "h"},
        {12, "i"}, {13, "j"}, {14, "k"}, {15, "l"}, {16, "m"}, {17, "n"}, {18, "o"}, {19, "p"},
        {20, "q"}, {21, "r"}, {22, "s"}, {23, "t"}, {24, "u"}, {25, "v"}, {26, "w"}, {27, "x"},
        {28, "y"}, {29, "z"},
        {30, "1"}, {31, "2"}, {32, "3"}, {33, "4"}, {34, "5"}, {35, "6"}, {36, "7"}, {37, "8"},
        {38, "9"}, {39, "0"},
        {40, "return"}, {41, "escape"}, {42, "backspace"}, {43, "tab"}, {44, "space"},
        {45, "-"}, {46, "="}, {47, "["}, {48, "]"}, {49, "\\"}, {51, ";"}, {52, "'"}, {53, "`"},
        {54, ","}, {55, "."}, {56, "/"}, {57, "capslock"},
        {58, "f1"}, {59, "f2"}, {60, "f3"}, {61, "f4"}, {62, "f5"}, {63, "f6"}, {64, "f7"},
        {65, "f8"}, {66, "f9"}, {67, "f10"}, {68, "f11"}, {69, "f12"},
        {70, "print"}, {71, "scrolllock"}, {72, "pause"},
        {73, "insert"}, {74, "home"}, {75, "pageup"}, {76, "delete"}, {77, "end"},
        {78, "pagedown"}, {79, "right"}, {80, "left"}, {81, "down"}, {82, "up"},
        {83, "numlock"},
        {84, "numpad/"}, {85, "numpad*"}, {86, "numpad-"}, {87, "numpad+"}, {88, "numpadenter"},
        {89, "numpad1"}, {90, "numpad2"}, {91, "numpad3"}, {92, "numpad4"}, {93, "numpad5"},
        {94, "numpad6"}, {95, "numpad7"}, {96, "numpad8"}, {97, "numpad9"}, {98, "numpad0"},
        {99, "numpad."},
        {224, "lctrl"}, {225, "lshift"}, {226, "lalt"}, {227, "lgui"},
        {228, "rctrl"}, {229, "rshift"}, {230, "ralt"}, {231, "rgui"},
    };
    return names;
}

const std::map<std::string, int>& name_to_sdl_scancode() {
    static const std::map<std::string, int> table = [] {
        std::map<std::string, int> m;
        for (const auto& [code, name] : sdl_scancode_names()) {
            m[name] = code;
        }

        static const std::map<std::string, std::vector<std::string>> aliases = {
            {"return", {"enter"}},
            {"escape", {"esc"}},
            {"backspace", {"bksp"}},
            {"capslock", {"caps"}},
            {"print", {"printscreen", "prtsc"}},
            {"scrolllock", {"scroll"}},
            {"pageup", {"pgup"}},
            {"pagedown", {"pgdn"}},
            {"numlock", {"num"}},
            {"delete", {"del"}},
            {"insert", {"ins"}},
            {"numpad/", {"kp/", "kpdiv", "numpaddivide"}},
            {"numpad*", {"kp*", "kpmul", "numpadmultiply", "numpadx"}},
            {"numpad-", {"kp-", "kpminus", "numpadminus", "kpdash"}},
            {"numpad+", {"kp+", "kpplus", "numpadplus"}},
            {"numpadenter", {"kpenter", "keypadenter"}},
            {"numpad1", {"kp1", "np1", "keypad1", "numpad 1"}},
            {"numpad2", {"kp2", "np2", "keypad2", "numpad 2"}},
            {"numpad3", {"kp3", "np3", "keypad3", "numpad 3"}},
            {"numpad4", {"kp4", "np4", "keypad4", "numpad 4"}},
            {"numpad5", {"kp5", "np5", "keypad5", "numpad 5"}},
            {"numpad6", {"kp6", "np6", "keypad6", "numpad 6"}},
            {"numpad7", {"kp7", "np7", "keypad7", "numpad 7"}},
            {"numpad8", {"kp8", "np8", "keypad8", "numpad 8"}},
            {"numpad9", {"kp9", "np9", "keypad9", "numpad 9"}},
            {"numpad0", {"kp0", "np0", "keypad0", "numpad 0"}},
            {"numpad.", {"kp.", "kpperiod", "numpadperiod", "numpaddot"}},
        };
        for (const auto& [canon, alist] : aliases) {
            int code = m.at(canon);
            for (const auto& a : alist) m[a] = code;
        }
        return m;
    }();
    return table;
}

const std::map<int, int>& qt_key_to_sdl_scancode() {
    static const std::map<int, int> table = {
        {Qt::Key_A, 4}, {Qt::Key_B, 5}, {Qt::Key_C, 6}, {Qt::Key_D, 7},
        {Qt::Key_E, 8}, {Qt::Key_F, 9}, {Qt::Key_G, 10}, {Qt::Key_H, 11},
        {Qt::Key_I, 12}, {Qt::Key_J, 13}, {Qt::Key_K, 14}, {Qt::Key_L, 15},
        {Qt::Key_M, 16}, {Qt::Key_N, 17}, {Qt::Key_O, 18}, {Qt::Key_P, 19},
        {Qt::Key_Q, 20}, {Qt::Key_R, 21}, {Qt::Key_S, 22}, {Qt::Key_T, 23},
        {Qt::Key_U, 24}, {Qt::Key_V, 25}, {Qt::Key_W, 26}, {Qt::Key_X, 27},
        {Qt::Key_Y, 28}, {Qt::Key_Z, 29},
        {Qt::Key_1, 30}, {Qt::Key_2, 31}, {Qt::Key_3, 32}, {Qt::Key_4, 33},
        {Qt::Key_5, 34}, {Qt::Key_6, 35}, {Qt::Key_7, 36}, {Qt::Key_8, 37},
        {Qt::Key_9, 38}, {Qt::Key_0, 39},
        {Qt::Key_Return, 40}, {Qt::Key_Enter, 40}, {Qt::Key_Escape, 41},
        {Qt::Key_Backspace, 42}, {Qt::Key_Tab, 43}, {Qt::Key_Space, 44},
        {Qt::Key_Minus, 45}, {Qt::Key_Equal, 46}, {Qt::Key_BracketLeft, 47},
        {Qt::Key_BracketRight, 48}, {Qt::Key_Backslash, 49}, {Qt::Key_Semicolon, 51},
        {Qt::Key_Apostrophe, 52}, {Qt::Key_QuoteLeft, 53}, {Qt::Key_Comma, 54},
        {Qt::Key_Period, 55}, {Qt::Key_Slash, 56}, {Qt::Key_CapsLock, 57},
        {Qt::Key_F1, 58}, {Qt::Key_F2, 59}, {Qt::Key_F3, 60}, {Qt::Key_F4, 61},
        {Qt::Key_F5, 62}, {Qt::Key_F6, 63}, {Qt::Key_F7, 64}, {Qt::Key_F8, 65},
        {Qt::Key_F9, 66}, {Qt::Key_F10, 67}, {Qt::Key_F11, 68}, {Qt::Key_F12, 69},
        {Qt::Key_Print, 70}, {Qt::Key_ScrollLock, 71}, {Qt::Key_Pause, 72},
        {Qt::Key_Insert, 73}, {Qt::Key_Home, 74}, {Qt::Key_PageUp, 75},
        {Qt::Key_Delete, 76}, {Qt::Key_End, 77}, {Qt::Key_PageDown, 78},
        {Qt::Key_Right, 79}, {Qt::Key_Left, 80}, {Qt::Key_Down, 81},
        {Qt::Key_Up, 82}, {Qt::Key_NumLock, 83},
        {Qt::Key_Control, 224}, {Qt::Key_Shift, 225}, {Qt::Key_Alt, 226},
        {Qt::Key_Meta, 227},
    };
    return table;
}

const std::map<int, int>& qt_keypad_to_sdl_scancode() {
    static const std::map<int, int> table = {
        {Qt::Key_0, 98}, {Qt::Key_1, 89}, {Qt::Key_2, 90}, {Qt::Key_3, 91},
        {Qt::Key_4, 92}, {Qt::Key_5, 93}, {Qt::Key_6, 94}, {Qt::Key_7, 95},
        {Qt::Key_8, 96}, {Qt::Key_9, 97},
        {Qt::Key_Period, 99}, {Qt::Key_Plus, 87}, {Qt::Key_Minus, 86},
        {Qt::Key_Asterisk, 85}, {Qt::Key_Slash, 84}, {Qt::Key_Enter, 88},
        {Qt::Key_Equal, 103},
        {Qt::Key_Home, 95}, {Qt::Key_End, 89}, {Qt::Key_PageUp, 97},
        {Qt::Key_PageDown, 91}, {Qt::Key_Up, 96}, {Qt::Key_Down, 90},
        {Qt::Key_Left, 92}, {Qt::Key_Right, 94}, {Qt::Key_Insert, 98},
        {Qt::Key_Delete, 99},
    };
    return table;
}

std::pair<std::string, std::string> normalize_input_value(const std::string& valueIn) {
    std::string value = trim_input_value(valueIn);

    if (value.starts_with("j") || value.starts_with("mb")) {
        return {value, value};
    }

    try {
        std::size_t pos = 0;
        int num = std::stoi(value, &pos);
        if (pos == value.size()) {
            auto& names = sdl_scancode_names();
            auto it = names.find(num);
            std::string name = it != names.end() ? it->second : std::to_string(num);
            return {std::to_string(num), name + " (" + std::to_string(num) + ")"};
        }
    } catch (...) {
        // fall through
    }

    std::string alias;
    for (char c : value) {
        if (c == ' ') continue;
        alias += (char)std::tolower((unsigned char)c);
    }
    auto& n2s = name_to_sdl_scancode();
    auto it = n2s.find(alias);
    if (it != n2s.end()) {
        int num = it->second;
        auto& names = sdl_scancode_names();
        auto nit = names.find(num);
        std::string name = nit != names.end() ? nit->second : alias;
        return {std::to_string(num), name + " (" + std::to_string(num) + ")"};
    }

    return {value, value};
}

std::string canonical_input_key(const std::string& section, const std::string& key) {
    auto& defs = input_defs();
    auto secIt = defs.find(section);
    if (secIt != defs.end()) {
        for (const auto& canon : secIt->second) {
            if (canon == key) return canon;
        }
        std::string lower = key;
        std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
        for (const auto& canon : secIt->second) {
            std::string canonLower = canon;
            std::transform(canonLower.begin(), canonLower.end(), canonLower.begin(), ::tolower);
            if (canonLower == lower) return canon;
        }
    }
    return key;
}

int geolith_input_setting_for_device(int device) {
    switch (device) {
        case 1: return 1; // Neo Geo Joysticks
        case 2: return 2; // Mahjong
        case 3: return 3; // 4-Player
        case 4: return 0; // V-Liner: auto-detected from the loaded game
        case 5: return 0; // Irritating Maze: auto-detected from the loaded game
        default: return 1;
    }
}

bool is_analog_input_definition(const std::string& section, const std::string& key) {
    return section == "neogeoirrmaze" && (key == "XAxis" || key == "YAxis");
}

bool is_joystick_axis_binding(const std::string& valueIn) {
    return is_safe_jgrf_binding(trim_input_value(valueIn), true);
}

std::optional<std::string> normalize_input_binding_for_definition(
        const std::string& section,
        const std::string& key,
        const std::string& value) {
    const std::string canonicalKey = canonical_input_key(section, key);
    if (!is_known_input_definition(section, canonicalKey))
        return std::nullopt;

    const std::string stored = normalize_input_value(value).first;
    if (!is_safe_jgrf_binding(
            stored, is_analog_input_definition(section, canonicalKey))) {
        return std::nullopt;
    }
    return stored;
}

std::optional<std::string> jgrf_hotkey_action(int scancode) {
    // Keep this table synchronized with JGRF src/input.c's direct,
    // modifier-free frontend hotkeys. Shift+1..8 are intentionally omitted:
    // those only trigger input configuration while Shift is held.
    static const std::map<int, std::string> hotkeys = {
        {41, "Quit"},
        {43, "Open Menu"},
        {53, "Fast-forward"},
        {58, "Soft Reset"},
        {59, "Hard Reset"},
        {62, "Save State (Slot 0)"},
        {63, "Save State (Slot 1)"},
        {64, "Load State (Slot 0)"},
        {65, "Load State (Slot 1)"},
        {66, "Screenshot"},
        {69, "Toggle Cheats On/Off"},
        {9,  "Toggle Fullscreen/Windowed Mode"},
        {16, "Toggle Audio Playback (Mute/Unmute)"},
        {19, "Pause / Resume"},
    };

    auto it = hotkeys.find(scancode);
    if (it == hotkeys.end()) return std::nullopt;
    return it->second;
}

std::optional<std::string> jgrf_hotkey_action_for_binding(const std::string& value) {
    const auto normalized = normalize_input_value(value);
    const std::string& stored = normalized.first;
    if (stored.empty() || stored.starts_with("j") || stored.starts_with("mb")) {
        return std::nullopt;
    }

    try {
        std::size_t pos = 0;
        const int scancode = std::stoi(stored, &pos);
        if (pos != stored.size()) return std::nullopt;
        return jgrf_hotkey_action(scancode);
    } catch (...) {
        return std::nullopt;
    }
}

} // namespace goliath
